using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FO4RecordEditor.Services.Graph;


public readonly record struct GraphSourceMapEntry(
    int Start, int Length, int Line, int Depth, string NodeId, string? PinId)
{
    public bool Contains(int offset) => offset >= Start && offset < Start + Length;
}









public sealed class GraphSourceMap
{
    private readonly List<GraphSourceMapEntry> _entries = new();

    public IReadOnlyList<GraphSourceMapEntry> Entries => _entries;

    internal void Add(GraphSourceMapEntry entry) => _entries.Add(entry);








    public GraphSourceMapEntry? Find(int offset)
    {
        GraphSourceMapEntry? best = null;
        foreach (var entry in _entries)
        {
            if (!entry.Contains(offset)) continue;
            if (best == null || entry.Depth > best.Value.Depth) best = entry;
        }
        return best;
    }


    public GraphSourceMapEntry? FindByLine(int line)
    {
        GraphSourceMapEntry? best = null;
        foreach (var entry in _entries)
        {
            if (entry.Line != line) continue;
            if (best == null || entry.Depth > best.Value.Depth) best = entry;
        }
        return best;
    }


    public GraphSourceMapEntry? FunctionAt(int offset)
    {
        GraphSourceMapEntry? best = null;
        foreach (var entry in _entries)
        {
            if (entry.Depth != 0 || !entry.Contains(offset)) continue;
            if (best == null || entry.Start > best.Value.Start) best = entry;
        }
        return best;
    }
}


public sealed class PapyrusSourceWriterOptions
{
    public string Indent { get; set; } = "\t";

    public string NewLine { get; set; } = "\n";

    public bool EmitHeaderComment { get; set; } = true;


    public string? GeneratorNote { get; set; }
}










public sealed class PapyrusSourceWriter
{
    private readonly PapyrusSourceWriterOptions _options;
    private readonly StringBuilder _text = new();
    private readonly GraphSourceMap _map = new();
    private int _depth;
    private int _line = 1;

    public PapyrusSourceWriter(PapyrusSourceWriterOptions? options = null) =>
        _options = options ?? new PapyrusSourceWriterOptions();


    private static int Precedence(string op) => op switch
    {
        "||" => 1,
        "&&" => 2,
        "==" or "!=" or "<" or "<=" or ">" or ">=" => 3,
        "+" or "-" => 4,
        "*" or "/" or "%" => 5,
        _ => 6,
    };

    private const int UnaryPrecedence = 6;
    private const int CastPrecedence = 7;
    private const int PostfixPrecedence = 8;

    public string Write(IrScript script, out GraphSourceMap map)
    {
        _text.Clear();
        _depth = 0;
        _line = 1;

        if (_options.EmitHeaderComment) WriteHeaderComment(script);
        WriteHeaderLine(script);

        foreach (var declared in script.Structs) WriteStruct(declared);
        if (script.Imports.Count > 0)
        {
            Blank();
            foreach (var import in script.Imports) Line("Import " + import);
        }

        if (script.CustomEvents.Count > 0)
        {
            Blank();
            foreach (var declared in script.CustomEvents) Line("CustomEvent " + declared);
        }

        if (script.Variables.Count > 0 || script.Properties.Count > 0) Blank();
        foreach (var variable in script.Variables) Line(DeclarationText(variable.TypeName, variable.IsArray, variable.Name, variable.Flags, variable.InitialText));
        foreach (var property in script.Properties) Line(PropertyText(property));




        foreach (var callable in script.Callables.Where(c => string.IsNullOrWhiteSpace(c.StateName)))
        {
            Blank();
            WriteCallable(callable);
        }

        foreach (var state in script.Callables
                     .Where(c => !string.IsNullOrWhiteSpace(c.StateName))
                     .GroupBy(c => c.StateName!, StringComparer.OrdinalIgnoreCase))
        {
            Blank();
            var isAuto = string.Equals(script.AutoState, state.Key, StringComparison.OrdinalIgnoreCase);
            Line((isAuto ? "Auto State " : "State ") + state.Key);
            _depth++;
            var first = true;
            foreach (var callable in state)
            {
                if (!first) Blank();
                WriteCallable(callable);
                first = false;
            }
            _depth--;
            Line("EndState");
        }

        map = _map;
        return _text.ToString();
    }

    private void WriteHeaderComment(IrScript script)
    {


        Line("; Generated by FO4RecordEditor from a node graph.");
        Line("; Edit the graph, not this file.");
        if (!string.IsNullOrWhiteSpace(_options.GeneratorNote)) Line("; " + _options.GeneratorNote);
        Blank();
    }

    private void WriteHeaderLine(IrScript script)
    {
        var header = new StringBuilder("Scriptname " + script.Name);
        if (!string.IsNullOrWhiteSpace(script.Extends)) header.Append(" extends ").Append(script.Extends);
        foreach (var flag in script.Flags) header.Append(' ').Append(flag);
        Line(header.ToString());
    }

    private void WriteStruct(IrStruct declared)
    {
        Blank();
        Line("struct " + declared.Name);
        _depth++;
        foreach (var member in declared.Members)
            Line(TypeText(member.TypeName, member.IsArray) + " " + member.Name);
        _depth--;
        Line("endstruct");
    }

    private static string DeclarationText(
        string typeName, bool isArray, string name, IReadOnlyList<string> flags, string? initial)
    {
        var text = new StringBuilder(TypeText(typeName, isArray) + " " + name);
        if (initial != null) text.Append(" = ").Append(initial);
        foreach (var flag in flags) text.Append(' ').Append(flag);
        return text.ToString();
    }

    private static string PropertyText(IrProperty property)
    {
        var text = new StringBuilder(TypeText(property.TypeName, property.IsArray)
                                     + " Property " + property.Name);
        if (property.InitialText != null) text.Append(" = ").Append(property.InitialText);


        if (!property.Flags.Any(f =>
                f.Equals("Auto", StringComparison.OrdinalIgnoreCase)
                || f.Equals("AutoReadOnly", StringComparison.OrdinalIgnoreCase)))
        {
            text.Append(" Auto");
        }

        foreach (var flag in property.Flags) text.Append(' ').Append(flag);
        return text.ToString();
    }

    private void WriteCallable(IrCallable callable)
    {
        var start = _text.Length;
        var startLine = _line;

        var keyword = callable.IsEvent ? "Event" : "Function";
        var signature = new StringBuilder();

        if (!callable.IsEvent && callable.ReturnTypeName != null)
            signature.Append(TypeText(callable.ReturnTypeName, callable.ReturnIsArray)).Append(' ');

        signature.Append(keyword).Append(' ');
        if (!string.IsNullOrWhiteSpace(callable.RemoteObjectType))
            signature.Append(callable.RemoteObjectType).Append('.');
        signature.Append(callable.Name).Append('(');
        signature.Append(string.Join(", ", callable.Parameters.Select(ParameterText)));
        signature.Append(')');
        if (callable.IsGlobal) signature.Append(" global");

        Line(signature.ToString());
        _depth++;

        foreach (var local in callable.Locals)
            Line(TypeText(local.TypeName, local.IsArray) + " " + local.Name);
        if (callable.Locals.Count > 0 && callable.Body.Count > 0) Blank();

        foreach (var statement in callable.Body) WriteStatement(statement);

        _depth--;
        Line(callable.IsEvent ? "EndEvent" : "EndFunction");

        _map.Add(new GraphSourceMapEntry(
            start, _text.Length - start, startLine, 0, callable.EntryNodeId, null));
    }

    private static string ParameterText(IrParameter parameter)
    {
        var text = TypeText(parameter.TypeName, parameter.IsArray) + " " + parameter.Name;
        return parameter.DefaultText == null ? text : text + " = " + parameter.DefaultText;
    }

    private void WriteStatement(IrStatement statement)
    {
        var start = _text.Length;
        var startLine = _line;

        switch (statement)
        {
            case IrDefine define:
                Line(TypeText(define.TypeName, define.IsArray) + " " + define.Name
                     + (define.Value == null ? "" : " = " + Expression(define.Value, 0)));
                break;

            case IrAssign assign:
                Line(Expression(assign.Target, PostfixPrecedence) + " = " + Expression(assign.Value, 0));
                break;

            case IrExpressionStatement expression:
                Line(Expression(expression.Expression, 0));
                break;

            case IrReturn ret:
                Line(ret.Value == null ? "Return" : "Return " + Expression(ret.Value, 0));
                break;

            case IrIf branch:
                WriteIf(branch);
                break;

            case IrWhile loop:
                Line("While (" + Expression(loop.Condition, 0) + ")");
                _depth++;
                foreach (var inner in loop.Body) WriteStatement(inner);
                _depth--;
                Line("EndWhile");
                break;
        }

        if (statement.NodeId != null)
        {
            _map.Add(new GraphSourceMapEntry(
                start, _text.Length - start, startLine, _depth + 1, statement.NodeId, statement.PinId));
        }
    }

    private void WriteIf(IrIf branch)
    {
        for (int i = 0; i < branch.Branches.Count; i++)
        {
            var arm = branch.Branches[i];
            Line((i == 0 ? "If (" : "ElseIf (") + Expression(arm.Condition, 0) + ")");
            _depth++;
            foreach (var statement in arm.Body) WriteStatement(statement);
            _depth--;
        }

        if (branch.Else != null)
        {
            Line("Else");
            _depth++;
            foreach (var statement in branch.Else) WriteStatement(statement);
            _depth--;
        }

        Line("EndIf");
    }










    private string Expression(IrExpression expression, int parentPrecedence)
    {
        switch (expression)
        {
            case IrLiteral literal:
                return literal.Text;

            case IrName name:
                return name.Name;

            case IrSelf:
                return "Self";

            case IrParent:
                return "Parent";

            case IrMember member:
                return Expression(member.Target, PostfixPrecedence) + "." + member.Name;

            case IrIndex index:
                return Expression(index.Target, PostfixPrecedence)
                       + "[" + Expression(index.Index, 0) + "]";

            case IrCall call:
            {
                var arguments = string.Join(", ", call.Arguments.Select(a =>
                    a.Name == null ? Expression(a.Value, 0) : a.Name + " = " + Expression(a.Value, 0)));
                var target = call.Receiver == null
                    ? ""
                    : Expression(call.Receiver, PostfixPrecedence) + ".";
                return target + call.Name + "(" + arguments + ")";
            }

            case IrUnary unary:
            {
                var text = unary.Operator + Expression(unary.Operand, UnaryPrecedence);
                return parentPrecedence > UnaryPrecedence ? "(" + text + ")" : text;
            }

            case IrBinary binary:
            {
                int precedence = Precedence(binary.Operator);
                var text = Expression(binary.Left, precedence)
                           + " " + binary.Operator + " "


                           + Expression(binary.Right, precedence + 1);
                return parentPrecedence > precedence ? "(" + text + ")" : text;
            }

            case IrCast cast:
            {
                var text = Expression(cast.Value, CastPrecedence) + " as "
                           + TypeText(cast.TargetType, cast.TargetIsArray);
                return parentPrecedence > CastPrecedence ? "(" + text + ")" : text;
            }

            case IrTypeCheck check:
            {
                var text = Expression(check.Value, CastPrecedence) + " is "
                           + TypeText(check.TargetType, check.TargetIsArray);
                return parentPrecedence > CastPrecedence ? "(" + text + ")" : text;
            }

            case IrNewArray array:
                return "new " + array.ElementType + "[" + Expression(array.Size, 0) + "]";

            case IrNewStruct structure:
                return "new " + structure.StructName;

            default:
                return "None";
        }
    }

    private static string TypeText(string typeName, bool isArray) =>
        (string.IsNullOrEmpty(typeName) ? "var" : typeName) + (isArray ? "[]" : "");

    private void Line(string text)
    {
        for (int i = 0; i < _depth; i++) _text.Append(_options.Indent);
        _text.Append(text).Append(_options.NewLine);
        _line++;
    }

    private void Blank()
    {
        _text.Append(_options.NewLine);
        _line++;
    }
}
