using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FO4RecordEditor.Services.Graph.F4SE;















public sealed class F4SECppEmitter
{

    public const string UnimplementedMacro = "F4SE_BINDING_UNIMPLEMENTED";

    public const string AllowStubsMacro = "F4SE_BINDING_ALLOW_STUBS";

    private const string GeneratedBanner =
        "// Generated by FO4RecordEditor. Edit the graph, not this file.\n"
        + "// Text between the body markers is preserved across regeneration; everything else is not.";

    private readonly F4SETypeMap _map;

    public F4SECppEmitter(IEnumerable<string>? structNames = null) => _map = new F4SETypeMap(structNames);


    public string EmitHeader(PluginBinding plugin, ModuleBinding module)
    {
        var text = new StringBuilder();
        text.Append(GeneratedBanner).Append('\n');
        text.Append("#pragma once\n\n");
        text.Append("class VirtualMachine;\n\n");

        if (module.Structs.Count > 0)
        {
            text.Append("#include \"f4se/PapyrusStruct.h\"\n\n");
            foreach (var declared in module.Structs)
                text.Append($"DECLARE_EXTERN_STRUCT({declared.Name})\n");
            text.Append('\n');
        }

        text.Append($"namespace {NamespaceOf(plugin, module)}\n");
        text.Append("{\n");
        text.Append("\tvoid RegisterFuncs(VirtualMachine * vm);\n");
        text.Append("}\n");
        return text.ToString();
    }


    public string EmitSource(PluginBinding plugin, ModuleBinding module)
    {
        var ns = NamespaceOf(plugin, module);
        var types = module.Natives
            .SelectMany(TypesOf)
            .Concat(module.Structs.SelectMany(s => s.Members).Select(m => CppOf(m.Type, m.Unsigned)))
            .Where(t => t != null)
            .Select(t => t!)
            .ToList();

        var text = new StringBuilder();
        text.Append(GeneratedBanner).Append('\n');
        text.Append($"#include \"{HeaderFileName(plugin, module)}\"\n\n");
        foreach (var include in _map.RequiredIncludesFor(types))
            text.Append($"#include \"{include}\"\n");
        text.Append('\n');

        text.Append($"#ifndef {AllowStubsMacro}\n");
        text.Append($"#define {UnimplementedMacro}(name) \\\n");
        text.Append("\tstatic_assert(false, \"F4SE binding '\" name \"' has no implementation. \" \\\n");
        text.Append($"\t\t\"Write one, or define {AllowStubsMacro} to build without it.\")\n");
        text.Append("#else\n");
        text.Append($"#define {UnimplementedMacro}(name) ((void)0)\n");
        text.Append("#endif\n\n");

        text.Append($"namespace {ns}\n{{\n");

        foreach (var declared in module.Structs)
            text.Append($"\tDECLARE_STRUCT({declared.Name}, \"{declared.OwnerScript}\")\n");
        if (module.Structs.Count > 0) text.Append('\n');

        foreach (var native in module.Natives)
        {
            text.Append(StubFor(native));
            text.Append('\n');
        }

        text.Append("}\n\n");
        text.Append(RegisterFuncsFor(ns, module));
        return text.ToString();
    }


    private string StubFor(NativeBinding native)
    {
        var text = new StringBuilder();
        text.Append('\t').Append(SignatureOf(native)).Append('\n');
        text.Append("\t{\n");
        text.Append("\t\t").Append(F4SERegionMerge.Begin(native.FunctionName)).Append('\n');
        text.Append($"\t\t{UnimplementedMacro}(\"{native.PapyrusClass}.{native.FunctionName}\");\n");

        var returnStatement = ReturnStatementFor(native);
        if (returnStatement != null) text.Append("\t\t").Append(returnStatement).Append('\n');

        text.Append("\t\t").Append(F4SERegionMerge.End(native.FunctionName)).Append('\n');
        text.Append("\t}\n");
        return text.ToString();
    }


    public string SignatureOf(NativeBinding native)
    {
        var returnType = CppOf(native.ReturnType, native.ReturnUnsigned)?.Format() ?? "void";

        var parameters = new List<string>
        {
            native.IsGlobal
                ? $"{F4SETypeMap.StaticFunctionTag} * base"
                : $"{native.CppBaseType} * {ReceiverNameFor(native)}",
        };

        parameters.AddRange(native.Parameters.Select(p =>
            $"{CppOf(p.Type, p.Unsigned)?.Format() ?? "void"} {p.Name}"));

        return $"{returnType} {native.FunctionName}({string.Join(", ", parameters)})";
    }




    private string? ReturnStatementFor(NativeBinding native)
    {
        var type = CppOf(native.ReturnType, native.ReturnUnsigned);
        if (type == null || type.Name == "void") return null;



        return $"return {type.Format()}();";
    }

    private string RegisterFuncsFor(string ns, ModuleBinding module)
    {
        var text = new StringBuilder();
        text.Append($"void {ns}::RegisterFuncs(VirtualMachine * vm)\n{{\n");

        foreach (var native in module.Natives)
        {
            var returnType = CppOf(native.ReturnType, native.ReturnUnsigned) ?? new CppTypeRef("void");
            var parameters = native.Parameters
                .Select(p => CppOf(p.Type, p.Unsigned) ?? new CppTypeRef("void"))
                .ToList();

            var instantiation = F4SETypeMap.TemplateInstantiation(
                native.IsLatent, native.Arity, native.CppBaseType, returnType, parameters);

            text.Append("\tvm->RegisterFunction(\n");
            text.Append($"\t\tnew {instantiation}(\"{native.FunctionName}\", \"{native.PapyrusClass}\", "
                        + $"{ns}::{native.FunctionName}, vm));\n");
        }

        var flagged = module.Natives.Where(n => n.NoWait).ToList();
        if (flagged.Count > 0)
        {
            text.Append('\n');
            foreach (var native in flagged)
            {
                text.Append($"\tvm->SetFunctionFlags(\"{native.PapyrusClass}\", \"{native.FunctionName}\", "
                            + "IFunction::kFunctionFlag_NoWait);\n");
            }
        }

        text.Append("}\n");
        return text.ToString();
    }


    public string EmitRegistrationsHeader(PluginBinding plugin) =>
        GeneratedBanner + "\n"
        + "#pragma once\n\n"
        + "class VirtualMachine;\n\n"
        + "bool RegisterAllFuncs(VirtualMachine * vm);\n";

    public string EmitRegistrationsSource(PluginBinding plugin)
    {
        var text = new StringBuilder();
        text.Append(GeneratedBanner).Append('\n');
        text.Append($"#include \"{plugin.Name}Registrations.h\"\n\n");
        text.Append("#include \"f4se/PapyrusVM.h\"\n");
        foreach (var module in plugin.Modules)
            text.Append($"#include \"{HeaderFileName(plugin, module)}\"\n");
        text.Append('\n');

        text.Append("bool RegisterAllFuncs(VirtualMachine * vm)\n{\n");
        foreach (var module in plugin.Modules)
            text.Append($"\t{NamespaceOf(plugin, module)}::RegisterFuncs(vm);\n");
        text.Append("\treturn true;\n}\n");
        return text.ToString();
    }


    public static string NamespaceOf(PluginBinding plugin, ModuleBinding module) =>
        string.IsNullOrEmpty(module.CppNamespace)
            ? $"papyrus{plugin.Name}{module.Name}"
            : module.CppNamespace;

    public static string BaseFileName(PluginBinding plugin, ModuleBinding module) =>
        $"Papyrus{plugin.Name}{module.Name}";

    public static string HeaderFileName(PluginBinding plugin, ModuleBinding module) =>
        BaseFileName(plugin, module) + ".h";

    public static string SourceFileName(PluginBinding plugin, ModuleBinding module) =>
        BaseFileName(plugin, module) + ".cpp";








    private static string ReceiverNameFor(NativeBinding native)
    {
        var name = native.CppBaseType;
        int colon = name.LastIndexOf(':');
        if (colon >= 0) name = name[(colon + 1)..];
        if (name.Length == 0) return "self";

        var lowered = char.ToLowerInvariant(name[0]) + name[1..];
        return lowered == "base" ? "self" : lowered;
    }

    private CppTypeRef? CppOf(PapyrusTypeText type, bool unsigned) =>
        _map.TryToCpp(type, unsigned, out var cpp, out _) ? cpp : null;

    private IEnumerable<CppTypeRef> TypesOf(NativeBinding native)
    {
        var returnType = CppOf(native.ReturnType, native.ReturnUnsigned);
        if (returnType != null) yield return returnType;
        foreach (var parameter in native.Parameters)
        {
            var type = CppOf(parameter.Type, parameter.Unsigned);
            if (type != null) yield return type;
        }
    }
}
