using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FO4RecordEditor.Services.Graph.F4SE;

/// <summary>
/// Emits the <c>.psc</c> that declares a module's natives, the Papyrus half of the boundary.
/// </summary>
/// <remarks>
/// The same <see cref="NativeBinding"/> records the C++ emitter renders, rendered the other way. The
/// two files are therefore consistent by construction rather than by discipline, and the emit then
/// read back round trip proves the two renderers agree.
/// <para>
/// Latency and <c>NoWait</c> are deliberately absent from the output: no <c>.psc</c> can express
/// either, which the shipped <c>UI.psc</c> demonstrates by declaring a plain native that the C++
/// registers as latent.
/// </para>
/// </remarks>
public sealed class F4SEPapyrusHeaderEmitter
{
    private const string GeneratedBanner =
        "; Generated by FO4RecordEditor. Edit the graph, not this file.\n"
        + "; Declarations only. The implementations live in this plugin's C++.";

    /// <summary>The script file for one module.</summary>
    public string Emit(PluginBinding plugin, ModuleBinding module)
    {
        var text = new StringBuilder();
        text.Append(GeneratedBanner).Append('\n').Append('\n');
        text.Append(HeaderLineFor(module)).Append('\n');

        if (module.Structs.Count > 0)
        {
            foreach (var declared in module.Structs)
            {
                text.Append('\n');
                text.Append($"struct {declared.Name}\n");
                foreach (var member in declared.Members)
                    text.Append($"\t{TypeTextFor(member.Type, module)} {member.Name}\n");
                text.Append("endstruct\n");
            }
        }

        var natives = module.Natives
            .Where(n => n.PapyrusClass.Equals(module.ScriptName, StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (natives.Count > 0) text.Append('\n');
        foreach (var native in natives)
            text.Append(DeclarationFor(native, module)).Append('\n');

        return text.ToString();
    }

    /// <summary>
    /// The <c>Scriptname</c> line.
    /// </summary>
    /// <remarks>
    /// A module that declares only globals gets <c>Native Hidden</c> and extends nothing, which is
    /// the shape the shipped <c>InstanceData.psc</c> uses. One that extends a base script keeps the
    /// <c>Native</c> flag, since every function it declares is implemented in C++.
    /// </remarks>
    public static string HeaderLineFor(ModuleBinding module)
    {
        var line = new StringBuilder($"Scriptname {module.ScriptName}");
        if (!string.IsNullOrWhiteSpace(module.Extends)) line.Append($" extends {module.Extends}");
        line.Append(" Native Hidden");
        return line.ToString();
    }

    /// <summary>One <c>native</c> declaration.</summary>
    public string DeclarationFor(NativeBinding native, ModuleBinding module)
    {
        var parameters = native.Parameters.Select(p =>
        {
            var text = $"{TypeTextFor(p.Type, module)} {p.Name}";
            return p.IsOptional ? $"{text} = {p.DefaultLiteral}" : text;
        });

        var returnText = IsNone(native.ReturnType) ? "" : TypeTextFor(native.ReturnType, module) + " ";
        var tail = native.IsGlobal ? " native global" : " native";
        return $"{returnText}Function {native.FunctionName}({string.Join(", ", parameters)}){tail}";
    }

    /// <summary>
    /// A type as this script has to write it.
    /// </summary>
    /// <remarks>
    /// A struct owned by another script is written <c>Owner:Struct</c>. The shipped
    /// <c>ObjectReference.ApplyMaterialSwap</c> returns <c>MatSwap:RemapData[]</c> for exactly this
    /// reason, and emitting the bare name there would produce a declaration that does not resolve.
    /// A struct the module owns itself is written bare, as <c>MatSwap.psc</c> writes its own
    /// <c>RemapData</c>.
    /// </remarks>
    public string TypeTextFor(PapyrusTypeText type, ModuleBinding module)
    {
        if (type.Name.Contains(':')) return type.ToString();

        var owner = _structOwners.TryGetValue(type.Name, out var found) ? found : null;
        if (owner == null || owner.Equals(module.ScriptName, StringComparison.OrdinalIgnoreCase))
            return type.ToString();

        return new PapyrusTypeText($"{owner}:{type.Name}", type.IsArray).ToString();
    }

    private readonly Dictionary<string, string> _structOwners;

    public F4SEPapyrusHeaderEmitter(PluginBinding? plugin = null)
    {
        _structOwners = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (plugin == null) return;
        foreach (var declared in plugin.AllStructs) _structOwners[declared.Name] = declared.OwnerScript;
    }

    private static bool IsNone(PapyrusTypeText type) =>
        !type.IsArray && type.Name.Equals("None", StringComparison.OrdinalIgnoreCase);

    /// <summary>Where a module's script is written, relative to the output root.</summary>
    public static string ScriptFileName(ModuleBinding module) =>
        "Data/Scripts/Source/User/" + module.ScriptName.Replace(':', '/') + ".psc";

    /// <summary>
    /// The declarations this emitter would write, in the form the cross check compares.
    /// </summary>
    /// <remarks>
    /// Lets the round trip check the emitted C++ against the emitted Papyrus without parsing the
    /// text back, which would only prove the parser and the emitter agree about syntax.
    /// </remarks>
    public IReadOnlyList<OracleNative> DeclarationsOf(ModuleBinding module) =>
        module.Natives
            .Where(n => n.PapyrusClass.Equals(module.ScriptName, StringComparison.OrdinalIgnoreCase))
            .Select(n => new OracleNative(
                n.PapyrusClass,
                n.FunctionName,
                n.ReturnType,
                n.Parameters.Select(p => p.Type).ToList(),
                n.IsGlobal))
            .ToList();
}
