<Project>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <DocumentationFile></DocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <NoWarn>$(NoWarn);CS1591;CS1066;CS1573;CS0108;CS1574;CS1570;CS0419;CA2022;CS1711;CS8524;CS0628;CA1416;CS0219;CS0169;CS0109</NoWarn>
    </PropertyGroup>

    <Target Name="ClearLocalNuGetPackages" AfterTargets="Build" Condition="'$(GeneratePackageOnBuild)' == 'true'">
        <PropertyGroup>
            <NuGetPackagesPath>$(USERPROFILE)\.nuget\packages</NuGetPackagesPath>

            <CurrentPackageId Condition="'$(PackageId)' != ''">$(PackageId)</CurrentPackageId>
            <CurrentPackageId Condition="'$(CurrentPackageId)' == '' AND '$(AssemblyName)' != ''">$(AssemblyName)</CurrentPackageId>
            <CurrentPackageId Condition="'$(CurrentPackageId)' == ''">$(MSBuildProjectName)</CurrentPackageId>

            <CurrentPackageIdLower>$(CurrentPackageId.ToLowerInvariant())</CurrentPackageIdLower>
        </PropertyGroup>

        <Message Text="Clearing local NuGet package cache for $(CurrentPackageId)..." Importance="high" />

        <Exec Condition="'$(OS)' == 'Windows_NT'"
              Command="if exist &quot;$(NuGetPackagesPath)\$(CurrentPackageIdLower)&quot; ( echo Deleting $(NuGetPackagesPath)\$(CurrentPackageIdLower) &amp;&amp; rd /s /q &quot;$(NuGetPackagesPath)\$(CurrentPackageIdLower)&quot; )"
              ContinueOnError="true" />

        <Exec Condition="'$(OS)' != 'Windows_NT'"
              Command="if [ -d &quot;$(NuGetPackagesPath)/$(CurrentPackageIdLower)&quot; ]; then echo &quot;Deleting $(NuGetPackagesPath)/$(CurrentPackageIdLower)&quot;; rm -rf &quot;$(NuGetPackagesPath)/$(CurrentPackageIdLower)&quot;; fi"
              ContinueOnError="true" />

        <Message Text="Finished clearing local NuGet package cache for $(CurrentPackageId)." Importance="high" />
    </Target>

</Project>