using System.Text.Json;

namespace FO4RecordEditor.Services;

public static class ConditionFunctions
{
    private static readonly string[] Table =
    {
        "CanPayCrimeGold=Faction",
        "CurrentFurnitureHasKeyword=Keyword",
        "DialogueGetAv=ActorValue",
        "DialogueGetItemCount=BaseObject",
        "DialogueHasPerk=Perk",
        "EPAlchemyEffectHasKeyword=Keyword",
        "EPIsDamageType=DamageType",
        "EPMagic_SpellHasKeyword=Keyword",
        "EPMagic_SpellHasSkill=ActorValue",
        "Exists=Reference",
        "GetActionDataByte=Integer",
        "GetActionDataFlag=Integer",
        "GetActionDataShort=Integer",
        "GetAngle=Axis",
        "GetBaseValue=ActorValue",
        "GetCombatTargetHasKeyword=Keyword",
        "GetComponentCount=BaseObject",
        "GetCrime=Actor,CrimeType",
        "GetCrimeGold=FactionNull",
        "GetCrimeGoldNonviolent=FactionNull",
        "GetCrimeGoldViolent=FactionNull",
        "GetCurrentCastingType=CastingSource",
        "GetCurrentDeliveryType=CastingSource",
        "GetDeadCount=ActorBase",
        "GetDetected=Actor",
        "GetDistance=Reference",
        "GetEquipped=BaseObject",
        "GetEquippedItemType=CastingSource",
        "GetEventData=Event,EventData",
        "GetFactionCombatReaction=Faction,Faction",
        "GetFactionRank=Faction",
        "GetFactionRankDifference=Faction,Actor",
        "GetFactionRelation=Actor",
        "GetGlobalValue=Global",
        "GetGraphVariableFloat=String",
        "GetGraphVariableInt=String",
        "GetHeadingAngle=Reference",
        "GetInCell=Cell",
        "GetInCellParam=Cell,Reference",
        "GetInContainer=Reference",
        "GetInCurrentLocation=Location",
        "GetInCurrentLocationAlias=Alias",
        "GetInCurrentLocationFormList=FormList",
        "GetInFaction=Faction",
        "GetInIronSights=Reference",
        "GetInSameCell=Reference",
        "GetInSharedCrimeFaction=Reference",
        "GetInWorldspace=WorldSpace",
        "GetInZone=EncounterZone",
        "GetInfamy=FactionNull",
        "GetInfamyNonViolent=FactionNull",
        "GetInfamyViolent=FactionNull",
        "GetIsAliasRef=Alias",
        "GetIsAlignment=Alignment",
        "GetIsClass=Class",
        "GetIsClassDefault=Class",
        "GetIsCreatureType=Integer",
        "GetIsCrimeFaction=Faction",
        "GetIsCurrentPackage=Package",
        "GetIsCurrentWeather=Weather",
        "GetIsEditorLocation=Location",
        "GetIsEditorLocationAlias=Alias",
        "GetIsID=BaseObject",
        "GetIsObjectType=FormType",
        "GetIsRace=Race",
        "GetIsReference=Reference",
        "GetIsSex=Sex",
        "GetIsUsedItem=BaseObject",
        "GetIsUsedItemEquipType=EquipType",
        "GetIsUsedItemType=FormType",
        "GetIsVoiceType=VoiceType",
        "GetItemCount=BaseObject",
        "GetKeywordDataForAlias=Alias,Keyword",
        "GetKeywordDataForCurrentLocation=Keyword",
        "GetKeywordDataForLocation=Location,Keyword",
        "GetKeywordItemCount=Keyword",
        "GetLineOfSight=Reference",
        "GetLocationAliasCleared=Alias",
        "GetLocationAliasRefTypeAliveCount=Alias,LocationRefType",
        "GetLocationAliasRefTypeDeadCount=Alias,LocationRefType",
        "GetLocationCleared=Location",
        "GetNumericPackageData=Packdata",
        "GetPCEnemyofFaction=Faction",
        "GetPCExpelled=Faction",
        "GetPCFactionAttack=Faction",
        "GetPCFactionMurder=Faction",
        "GetPCMiscStat=MiscStat",
        "GetPathingCurrentSpeedAngle=Axis",
        "GetPathingTargetAngleOffset=Axis",
        "GetPathingTargetOffset=Axis",
        "GetPathingTargetSpeedAngle=Axis",
        "GetPermanentValue=ActorValue",
        "GetPlayerControlsDisabled=Integer,Integer,Integer",
        "GetPos=Axis",
        "GetQuestCompleted=Quest",
        "GetQuestRunning=Quest",
        "GetRefTypeAliveCount=Location,LocationRefType",
        "GetRefTypeDeadCount=Location,LocationRefType",
        "GetRelationshipRank=Actor",
        "GetRelativeAngle=Reference,Axis",
        "GetSceneActionPercent=Scene,Integer",
        "GetShouldAttack=Actor",
        "GetShouldHelp=Actor",
        "GetSpellUsageNum=EffectItem",
        "GetStage=Quest",
        "GetStageDone=Quest,QuestStage",
        "GetStartingAngle=Axis",
        "GetStartingPos=Axis",
        "GetStolenItemValue=Faction",
        "GetStolenItemValueNoCrime=Faction",
        "GetTalkedToPCParam=Actor",
        "GetTargetHeight=Reference",
        "GetThreatRatio=Actor",
        "GetVATSBackAreaFree=Reference",
        "GetVATSBackLeftAreaFree=Reference",
        "GetVATSBackLeftTargetVisible=Reference",
        "GetVATSBackRightAreaFree=Reference",
        "GetVATSBackRightTargetVisible=Reference",
        "GetVATSBackTargetVisible=Reference",
        "GetVATSFrontAreaFree=Reference",
        "GetVATSFrontTargetVisible=Reference",
        "GetVATSLeftAreaFree=Reference",
        "GetVATSLeftTargetVisible=Reference",
        "GetVATSRightAreaFree=Reference",
        "GetVATSRightMinusLeftAreaFree=Reference",
        "GetVATSRightTargetVisible=Reference",
        "GetVATSTargetLimbVisible=Reference",
        "GetVATSValue=Integer,Integer",
        "GetVMQuestVariable=Quest,String",
        "GetVMScriptVariable=String,String",
        "GetValue=ActorValue",
        "GetValuePercent=ActorValue",
        "GetVelocity=Axis",
        "GetWithinActivateDistance=Reference",
        "GetWithinDistance=Reference,Float",
        "GetWithinPackageLocation=Packdata",
        "GetWorkshopObjectCount=BaseObject",
        "GetWorkshopResourceDamage=ActorValue",
        "HasActorRefOwner=Actor",
        "HasAssociationType=Actor,AssociationType",
        "HasAssociationTypeAny=AssociationType",
        "HasBoundWeaponEquipped=CastingSource",
        "HasEquippedSpell=CastingSource",
        "HasFamilyRelationship=Actor",
        "HasKey=Reference",
        "HasKeyword=Keyword",
        "HasLinkedRef=Keyword",
        "HasMagicEffect=BaseEffect",
        "HasMagicEffectKeyword=Keyword",
        "HasParentRelationship=Actor",
        "HasPerk=Perk",
        "HasRefType=LocationRefType",
        "HasSameEditorLocationAsRef=Reference,Keyword",
        "HasSameEditorLocationAsRefAlias=Alias,Keyword",
        "HasSharedPowerGrid=Reference",
        "HasSpell=EffectItem",
        "HasVMScript=String",
        "HasValidRumorTopic=Quest",
        "IsActorRefOwner=Actor",
        "IsAttackType=Keyword",
        "IsCellOwner=Cell,Owner",
        "IsCloserToAThanB=Reference,Reference",
        "IsCombatTarget=Actor",
        "IsCurrentFurnitureObj=Furniture",
        "IsCurrentFurnitureRef=Reference",
        "IsCurrentSpell=EffectItem,CastingSource",
        "IsFurnitureEntryType=BaseObject",
        "IsFurnitureExitType=BaseObject",
        "IsHostileToActor=Actor",
        "IsInCombat=Integer",
        "IsInCriticalStage=CriticalStage",
        "IsInList=FormList",
        "IsInSameCurrentLocationAsRef=Reference,Keyword",
        "IsInSameCurrentLocationAsRefAlias=Alias,Keyword",
        "IsInSameSpace=Reference",
        "IsKiller=Actor",
        "IsKillerObject=FormList",
        "IsLastIdlePlayed=IdleForm",
        "IsLimbGone=Integer",
        "IsLinkedTo=Reference,Keyword",
        "IsLocationAliasLoaded=Alias",
        "IsLocationLoaded=Location",
        "IsNullPackageData=Packdata",
        "IsOwnedBy=Actor",
        "IsOwner=Owner",
        "IsPlayerActionActive=Integer",
        "IsPlayerGrabbedRef=Reference",
        "IsPlayerInRegion=Region",
        "IsPlayerListening=Float",
        "IsSceneActionComplete=Scene,Integer",
        "IsScenePlaying=Scene",
        "IsSeatOccupied=Keyword",
        "IsSpellTarget=EffectItem",
        "IsTalkingActivatorActor=Actor",
        "IsWardState=WardState",
        "IsWarningAbout=FormList",
        "IsWeaponInList=FormList",
        "IsWeaponSkillType=ActorValue",
        "LastCrippledCondition=ActorValue",
        "LocationAliasHasKeyword=Alias,Keyword",
        "LocationAliasIsLocation=Alias,Location",
        "LocationHasKeyword=Keyword",
        "LocationHasRefType=LocationRefType",
        "MenuMode=Integer",
        "ModdedItemHasKeyword=Keyword",
        "MovementIdleMatches=Integer,Integer",
        "ObjectTemplateItem_HasKeyword=Keyword",
        "ObjectTemplateItem_HasUniqueKeyword=Keyword",
        "PlayerKnows=BaseObject",
        "SameFaction=Actor",
        "SameRace=Actor",
        "SameSex=Actor",
        "ShouldAttackKill=Actor",
        "SpellHasCastingPerk=Perk",
        "SpellHasKeyword=CastingSource,Keyword",
        "WornApparelHasKeywordCount=Keyword",
        "WornCoversBipedSlot=Integer",
        "WornHasKeyword=Keyword",
        "WouldBeStealing=Reference",
        "WouldRefuseCommand=Reference",
    };

    private static readonly Dictionary<string, string[]> ByName = Build();

    private static Dictionary<string, string[]> Build()
    {
        var d = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);
        foreach (var line in Table)
        {
            int eq = line.IndexOf('=');
            d[line[..eq]] = line[(eq + 1)..].Split(',', StringSplitOptions.RemoveEmptyEntries);
        }
        return d;
    }

    public static string[] ParamsOf(string function) =>
        ByName.TryGetValue(function ?? "", out var p) ? p : Array.Empty<string>();

    public static (string kind, string types) EditorFor(string paramType) => paramType switch
    {
        "Actor"           => ("record", "PlacedNpc"),
        "ActorBase"       => ("record", "Npc"),
        "ActorValue"      => ("record", "ActorValueInformation"),
        "AssociationType" => ("record", "AssociationType"),
        "BaseEffect"      => ("record", "MagicEffect"),
        "BaseObject"      => ("record", ""),
        "Cell"            => ("record", "Cell"),
        "Class"           => ("record", "Class"),
        "DamageType"      => ("record", "DamageType"),
        "EffectItem"      => ("record", "Ingestible,ObjectEffect,Ingredient,Spell"),
        "EncounterZone"   => ("record", "EncounterZone"),
        "EquipType"       => ("record", "EquipType"),
        "EventData"       => ("record", "Location,Keyword,FormList"),
        "Faction"         => ("record", "Faction"),
        "FactionNull"     => ("record", "Faction"),
        "FormList"        => ("record", "FormList"),
        "Furniture"       => ("record", "Furniture"),
        "Global"          => ("record", "Global"),
        "IdleForm"        => ("record", "IdleAnimation"),
        "Keyword"         => ("record", "Keyword"),
        "Location"        => ("record", "Location"),
        "LocationRefType" => ("record", "LocationReferenceType"),
        "Owner"           => ("record", "Faction,Npc"),
        "Package"         => ("record", "Package"),
        "Perk"            => ("record", "Perk"),
        "Quest"           => ("record", "Quest"),
        "Race"            => ("record", "Race"),
        "Reference"       => ("record", "PlacedObject,PlacedNpc"),
        "Region"          => ("record", "Region"),
        "Scene"           => ("record", "Scene"),
        "VoiceType"       => ("record", "VoiceType"),
        "Weather"         => ("record", "Weather"),
        "WorldSpace"      => ("record", "Worldspace"),
        "String" or "Event" => ("text", ""),
        _ => ("number", ""),
    };

    public static string AsJson() => JsonSerializer.Serialize(
        ByName.ToDictionary(
            kv => kv.Key,
            kv => kv.Value.Select(p =>
            {
                var (kind, types) = EditorFor(p);
                return new { label = Spaced(p), kind, types };
            }).ToArray()));

    private static string Spaced(string pascal)
    {
        var sb = new System.Text.StringBuilder(pascal.Length + 4);
        for (int i = 0; i < pascal.Length; i++)
        {
            if (i > 0 && char.IsUpper(pascal[i]) && !char.IsUpper(pascal[i - 1])) sb.Append(' ');
            sb.Append(pascal[i]);
        }
        return sb.ToString();
    }
}
